export const images = {
  recent1: require('../assets/Images/Player/main.png'),
  recent2: require('../assets/Images/mainLana.png'),
  recent3: require('../assets/Images/main3.png'),
  recent4: require('../assets/Images/main4.png'),
  wrap1:require('../assets/Images/wrap.png'),
  wrap2:require('../assets/Images/review.png'),
  wrap3:require('../assets/Images/artist.png'),
  ed1:require('../assets/Images/E3.png'),
  ed2:require('../assets/Images/E2.png'),
  ed3:require('../assets/Images/sza.png'),
  play1:require('../assets/Images/play.png'),
  search1:require('../assets/Images/CoverDisc.png'),
  search2:require('../assets/Images/Icon.png'),
  lib1:require('../assets/Images/Library/4.png'),
  lib2:require('../assets/Images/Library/2.png'),
  lib3:require('../assets/Images/Library/1.png'),
  lib4:require('../assets/Images/Library/3.png'),
  lib5:require('../assets/Images/Library/5.png'),
  pin1:require('../assets/Images/Library/Group1.png'),
  pin2:require('../assets/Images/Library/Group2.png'),
  profile:require('../assets/Images/Library/icon.png'),
  login:require('../assets/Images/Login/login.png'),
  google:require('../assets/Images/Login/google.png'),
  apple:require('../assets/Images/Login/apple.png'),
  facebook:require('../assets/Images/Login/facebook.png'),
  download:require('../assets/Images/AlbumView/M.png'),
  cover101: require('../assets/Images/Player/main.png')
};
